server {
    listen 80;
    server_name ~^(?<people_user>[a-z_][a-z0-9_-]{0,31})\.p\.meyerbrief\.de$;
    root /home/$people_user/public_html;
    index index.html;
    location / { try_files $uri $uri/ =404; }
    location ~ /\. { deny all; }
}

server {
    listen 80 default_server;
    server_name _;
    return 444;
}
